env_file:
  - .env
services:
  server:
    image: maven:3-amazoncorretto-23
    command: mvn clean spring-boot:run
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - ../:/usr/src/collector:rw
    working_dir: /usr/src/collector
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/collector-db
      - SPRING_DATASOURCE_USERNAME=POSTGRES_USER
      - SPRING_DATASOURCE_PASSWORD=POSTGRES_PASSWORD
  database:
    image: postgres:latest
    restart: always
    container_name: database
    environment:
      - POSTGRES_DB=collector-db
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
    ports:
      - 5432
    volumes:
      - ../db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d collector-db"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
